services:
  - type: web
    name: multi-agent-backend
    env: node
    region: oregon
    plan: standard # IMPORTANTE: Necesitas al menos standard para 2GB RAM
    buildCommand: |
      echo "🔧 Installing dependencies..."
      npm ci --include=dev
      echo "📦 Building TypeScript..."
      npm run build
      echo "✅ Build complete. Checking output..."
      ls -la dist/
      echo "🎯 Main file: dist/index.js"
      test -f dist/index.js && echo "✅ dist/index.js exists" || (echo "❌ dist/index.js NOT FOUND" && exit 1)
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false # Configurar en Render Dashboard
      - key: REDIS_URL
        sync: false # NUEVO: Necesario para WebSockets
      - key: ANTHROPIC_API_KEY
        sync: false # Configurar en Render Dashboard
      - key: GITHUB_TOKEN
        sync: false # Configurar en Render Dashboard
      - key: JWT_SECRET
        sync: false # Configurar en Render Dashboard
      - key: SESSION_SECRET
        sync: false # Configurar en Render Dashboard
      - key: FRONTEND_URL
        sync: false # Tu URL de Firebase
      - key: CORS_ORIGIN
        sync: false # Tu URL de Firebase
      - key: WORKSPACE_PATH
        value: /tmp/workspaces # Temporal, se pierde en cada deploy
      - key: UPLOAD_PATH
        value: /tmp/uploads # Temporal
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048" # Para evitar errores de memoria
    healthCheckPath: /health
    autoDeploy: false # Desactivar auto-deploy para control manual
